services:
  postgres:
    image: postgres:17
    container_name: driva-postgres
    environment: 
      POSTGRES_USER: driva 
      POSTGRES_PASSWORD: driva
      POSTGRES_DB: driva-dw
    ports: 
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Bindmount.
      - postgres-data:/var/lib/postgresql/data # Volume nomeado.
    networks:
      - driva-net

  n8n:
    image: n8nio/n8n:latest
    container_name: driva-n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: driva-dw
      DB_POSTGRESDB_USER: driva
      DB_POSTGRESDB_PASSWORD: driva
      N8N_RUNNERS_ENABLED: "false"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "admin"
    depends_on:
      - postgres
    volumes: 
      - n8n-data:/home/node/.n8n
    networks:
      - driva-net

  api: 
    build: ./api
    container_name: driva-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: driva-dw
      DB_USR: driva
      DB_PSW: driva
      API_KEY: driva_test_key_abc123xyz789 # Para não ficar "hardcoded".
    depends_on:
      - postgres
    networks:
      - driva-net

volumes: 
  postgres-data:
  n8n-data:

networks:
  driva-net:
    driver: bridge # Permite comunicação entre múltiplos containers.

